services:
    # 1. The OAuth Provider Logic
    booskit.gtawoauth.auth.provider:
        class: booskit\gtawoauth\auth\provider\gtaw
        arguments:
            - '@config'
            - '@request'
            - '@controller.helper'
        tags:
            - { name: auth.provider.oauth }

    # 2. Listener to load CSS and Language
    booskit.gtawoauth.listener:
        class: booskit\gtawoauth\event\listener
        arguments:
            - '@template'
            - '@user'
        tags:
            - { name: event.listener }

    # 3. ACP Controller
    booskit.gtawoauth.controller.acp:
        class: booskit\gtawoauth\controller\acp\settings
        arguments:
            - '@config'
            - '@request'
            - '@template'
            - '@user'
            - '@log'

    # 4. UCP Controller
    booskit.gtawoauth.controller.ucp:
        class: booskit\gtawoauth\controller\ucp\link
        arguments:
            - '@config'
            - '@request'
            - '@template'
            - '@user'
            - '@booskit.gtawoauth.auth.provider'
            - '@dbal.conn'
            - '@controller.helper'
            - '@language'
            - '%core.table_prefix%'

    # 5. Callback Controller
    booskit.gtawoauth.controller.callback:
        class: booskit\gtawoauth\controller\callback
        arguments:
            - '@config'
            - '@request'
            - '@user'
            - '@auth'
            - '@booskit.gtawoauth.auth.provider'
            - '@dbal.conn'
            - '@controller.helper'
            - '@language'
            - '%core.table_prefix%'
