booskit_awards_add_award:
    path: /awards/add/{user_id}
    defaults: { _controller: 'booskit.awards.controller.main:add_award' }
    requirements:
        user_id: \d+

booskit_awards_remove_award:
    path: /awards/remove/{award_id}
    defaults: { _controller: 'booskit.awards.controller.main:remove_award' }
    requirements:
        award_id: \d+
