services:
    booskit.awards.service.award_manager:
        class: booskit\awards\service\award_manager
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@user'
            - '%booskit.awards.tables.users%'
            - '%booskit.awards.tables.definitions%'

    booskit.awards.controller.acp.settings:
        class: booskit\awards\controller\acp\settings
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@request'
            - '@template'
            - '@user'
            - '@log'
            - '@booskit.awards.service.award_manager'
            - '%core.table_prefix%'

    booskit.awards.controller.main:
        class: booskit\awards\controller\main
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@request'
            - '@template'
            - '@user'
            - '@controller.helper'
            - '@auth'
            - '@log'
            - '@booskit.awards.service.award_manager'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%core.table_prefix%'

    booskit.awards.listener:
        class: booskit\awards\event\listener
        arguments:
            - '@template'
            - '@user'
            - '@controller.helper'
            - '@auth'
            - '@booskit.awards.service.award_manager'
        tags:
            - { name: event.listener }

parameters:
    booskit.awards.tables.users: %core.table_prefix%booskit_awards_users
    booskit.awards.tables.definitions: %core.table_prefix%booskit_awards_definitions
