services:
    booskit.gtawtracker.listener:
        class: booskit\gtawtracker\event\listener
        arguments:
            - '@config'
            - '@template'
            - '@user'
            - '@controller.helper'
            - '@request'
            - '@dbal.conn'
            - '%core.table_prefix%'
        tags:
            - { name: event.listener }

    booskit.gtawtracker.controller.ajax:
        class: booskit\gtawtracker\controller\ajax
        arguments:
            - '@config'
            - '@request'
            - '@user'
            - '@template'
            - '@booskit.gtawoauth.auth.provider'
            - '@dbal.conn'
            - '%core.table_prefix%'
            - '@language'
